version: '3.8'
services:
  lora-api-enhanced-v2:  
    container_name: lora-sensor-api-v5
    build: .
    ports:
      - "5002:5002"
    volumes:
      - ./data:/app/data
      - ./config:/app/config
      - ./static:/app/static
    environment:
      - PYTHONUNBUFFERED=1
      






