version: '3.8'
services:
  lora-sensor-network:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - ./data:/app/data
      - ./config:/app/config
      - ./static:/app/static
    environment:
      - PYTHONUNBUFFERED=1
      




